### ISSUE TITLE
Decide on a project out of the following ideas

### ISSUE THREAD

**Issue by GigaHierz** [DLT-developers-NFT-project/dlt-dev-nft-project#1]
1. Gamification of DLT Talents: to interact with different talents. 
For example
   - every talent recieves an animal 
   - the animal needs to be fed with interaction
   - whenever there is an interaction, based on the intensity, length, you merge different types of bodies/DNA
   - e.g. for a comment you get a toe, for a phone call a hand etc., group call color mix
   - goal is to have the most crazy looking animal (most fantastic)

2. Markeplace/ Platform where you can aquire a part/layer/percentage of a NFT : very diverse usecases, can applied to DeFi, art, marketing
3. Platform to create your own NFT (ex. OpenSea/ Cargo) : intesting to learn the process on creating NFTs
4. NFT Game (CryptoZombie Clone/ Mooncat) : Fun and easy way to learn; to engage people, interest them. [Here is an example](https://github.com/openberry-ac/cryptovipers)

[Examples for NFT projects](https://github.com/gianni-dalerta/awesome-nft#nft-art)

**Comment by aohnia** [comment]
Decided to proceed with a NFT Game DApp. 
Future developments may include development of a NFT Marketplace
